### ISSUE TITLE
Implement a nav toolbar above timeline

### ISSUE THREAD

**Issue by jlegrone** [L4GG/timeline#70]
Basic requirements:

- [ ] About L4GG link (http://lawyersforgoodgovernment.org)
- [ ] Donate link (https://actionnetwork.org/fundraising/support-lawyers-for-good-government-in-the-fight-to-protect-our-democracy)

Future Requirements:
- [ ] Filter by tag controls -- #5 
- [ ] Filter by date controls -- #26 
- [ ] Zoom controls -- #28 (not sure yet if this will go in the toolbar)

**Comment by sgeofrank** [comment]
Main brand background color is white.
Secondary background color is 323a65 (button backgrounds, menu backgrounds etc)
Primary accent color: 40b2e2

font file for headers: https://static-assets.strikinglycdn.com/fonts/themes/fresh/gothamrnd-book.woff generic sans-serif for normal text
